// <auto-generated />
using AiTodo.infrastructure.Persistance;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AiTodo.infrastructure.Migrations
{
    [DbContext(typeof(aitodoDBContext))] // Zamień YourDbContext na faktyczną nazwę Twojego DbContext!
    [Migration("20250513140931_Seeder")]
    partial class Seeder
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0"); // Zmień na swoją wersję EF Core

            modelBuilder.Entity("TwojaPrzestrzenNazw.Todo", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                b.Property<string>("EncodedTitle")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                // Dodaj tu inne właściwości swojej encji Todo

                b.HasKey("Id");

                b.ToTable("Todos");
            });
#pragma warning restore 612, 618
        }
    }
}